spring.application.name=activityservice
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/fitness-service-user
spring.datasource.username=postgres
spring.datasource.password=@root@123@

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

